apiVersion: v1
appVersion: "1.0"
description: Lidarr - Automatic downloader for music ^^
name: lidarr
version: 0.1.0
icon: https://github.com/naaga78/chartrizard/tree/main/charts/lidarr/logo/lidarr.png
